version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/tictactoe

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies

      - run: gradle test

      - run:
          name: Code coverage report
          command: |
            ./gradlew jacocoTestReport;

      - store_artifacts:
          path: build/reports/junit/html/
          destination: junit-test-report

      - store_artifacts:
          path: build/reports/jacoco/html/
          destination: jacoco-test-report